export const UI_FEATURE_TYPES = [
  // "alarm-modes",
  // "climate-fan-modes",
  // "climate-hvac-modes",
  // "climate-preset-modes",
  // "climate-swing-modes",
  // "climate-swing-horizontal-modes",
  // "counter-actions",
  // "cover-open-close",
  // "cover-position",
  // "cover-tilt-position",
  // "cover-tilt",
  // "fan-preset-modes",
  // "fan-speed",
  // "humidifier-modes",
  // "humidifier-toggle",
  // "lawn-mower-commands",
  // "light-brightness",
  // "light-color-temp",
  // "lock-commands",
  // "lock-open-door",
  "media-player-volume-slider",
  // "numeric-input",
  // "select-options",
  // "target-humidity",
  // "target-temperature",
  // "toggle",
  // "update-actions",
  // "vacuum-commands",
  // "water-heater-operation-modes",
] as const;
